### ISSUE TITLE
Issues configuring file

### ISSUE THREAD

**Issue by ItsRyleeDuhh** [4ndyZ/JoinMessagePlus#1]
Whenever I set the join and quit messages to true and replaced the message with what I want it to say, and restart the server, it resets back to being false. Not sure what is causing this. 
![Screenshot_1715](https://user-images.githubusercontent.com/76891145/111027044-c8727780-83bb-11eb-8885-d97d0e87681b.png)
![Screenshot_1716](https://user-images.githubusercontent.com/76891145/111027045-c8727780-83bb-11eb-82c6-66a2c0254e7d.png)
![Screenshot_1718](https://user-images.githubusercontent.com/76891145/111027046-c8727780-83bb-11eb-8220-f39c50b56045.png)

**Comment by 4ndyZ** [comment]
Hey @ItsRyleeDuhh I hope you were able to solve your problem on your own. 
If not feel free to reopen this issue.
