### ISSUE TITLE
Placeholderapi question

### ISSUE THREAD

**Issue by AggerTV** [4ndyZ/JoinMessagePlus#3]
Hello, I'm having trouble setting the messages correct with placeholderapi

Config:
`BungeeSupport:
  Enabled: false
AuthMeSupport:
  Enabled: false
JoinMessage:
  Enabled: true
  Message: '&8[&a+&8] %placeholderapi_luckperms_prefix%%player_name%'
QuitMessage:
  Enabled: true
  Message: '&8[&4-&8] %placeholderapi_luckperms_prefix%%player_name%'`

Output:
https://gyazo.com/5ad454834a2f4929571407c4f525a136

**Comment by 4ndyZ** [comment]
I hope you were able to solve your problem yourself.

If not feel free to reopen this issue.

**Comment by AggerTV** [comment]
> I hope you were able to solve your problem yourself. If not feel free to reopen this issue.

Yes I fixed it :)
But if you could reply here it would be great
https://github.com/4ndyZ/JoinMessagePlus/issues/4
